# Generated by Django 4.0 on 2021-12-30 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_remove_shop_type_alter_shop_proucts'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_type', to='shop.shoptype'),
        ),
    ]
