# Generated by Django 4.0 on 2021-12-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_shop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='type',
        ),
    ]
