# Generated by Django 4.0 on 2021-12-30 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_shop_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShopType',
        ),
    ]
