# Generated by Django 4.0 on 2021-12-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shoptype_shop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
