# Generated by Django 4.0 on 2021-12-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_cartitem_cart_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordered',
        ),
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('P', 'Paid'), ('N', 'Not paid'), ('C', 'Canceled')], default='N', max_length=1),
        ),
    ]
