# Generated by Django 3.2.10 on 2022-01-02 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
    ]
