# Generated by Django 3.2.10 on 2022-01-02 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_remove_product_shop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='created_by',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='uploads/default.jpg', upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(),
        ),
    ]
