# Generated by Django 3.2.10 on 2022-01-06 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_alter_shop_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='proucts',
        ),
    ]
