# Generated by Django 3.2.10 on 2022-01-06 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_shop_proucts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
        migrations.AddField(
            model_name='cart',
            name='total_price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='shop.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
