# Generated by Django 3.2.10 on 2022-01-10 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
