# Generated by Django 3.2.10 on 2022-01-12 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_remove_cartitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='owner',
            new_name='buyer',
        ),
    ]
