# Generated by Django 3.2.10 on 2022-01-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_rename_owner_cart_buyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='buyer',
            new_name='owner',
        ),
    ]
