# Generated by Django 3.2.10 on 2022-01-19 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_cart_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_available',
        ),
    ]
