# Generated by Django 3.2.10 on 2022-01-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_product_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shop',
        ),
    ]
