# Generated by Django 3.2.10 on 2022-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_cart_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
