# Generated by Django 3.2.10 on 2022-01-20 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='price',
            field=models.PositiveBigIntegerField(blank=True, default=0),
        ),
    ]
