# Generated by Django 4.0 on 2021-12-29 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^09\\d{9}$', message='Invalid phone number.')]),
        ),
    ]
